name: marlin_auto_build

on:
  push:
    paths:
      - 'builds/**'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: zisismaras/marlin_auto_build@master
